package LogfuzB;

import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;

public class LogFuz extends javax.swing.JFrame {

    private JTable tabel;
    private JLabel lblApl = new JLabel("");
    private DefaultTableModel model;
    private JScrollPane scrollPane;
    public static double Rm1[] = new double[16];
    public static double Rm2[] = new double[16];
    public static double Rm3[] = new double[16];
    public static double Rm4[] = new double[16];
    public static double AlfaTemp[] = new double[16];
    public static double Zn[] = new double[16];
    public static double zA;

    public LogFuz() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        merkHp = new javax.swing.JTextField();
        hargaHp = new javax.swing.JTextField();
        memoriHp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kameraHp = new javax.swing.JTextField();
        ramHp = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        rule = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        diagram = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        detailHitung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        kesesuaianLbl = new javax.swing.JLabel();
        kesesuaianLbl2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Implementasi Logika Fuzzy untuk Pemilihan Handphone dengan Menggunakan Metode FIS Tsukamoto");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Smartphone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 2, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel1.setText("Nama Smartphone");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("Memori Internal");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Harga");

        hargaHp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        hargaHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hargaHpKeyReleased(evt);
            }
        });

        memoriHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                memoriHpKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Kamera Utama");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setText("RAM");

        kameraHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kameraHpKeyReleased(evt);
            }
        });

        ramHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ramHpKeyReleased(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jButton2.setText("Clear Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        rule.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rule.setText("Rule");
        rule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jLabel2.setText("Rp");

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jLabel8.setText("MP");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jLabel11.setText("GB");

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jLabel12.setText("GB");

        diagram.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        diagram.setText("Diagram Alpha");
        diagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagramActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 102));
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        detailHitung.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        detailHitung.setText("Lihat Detail Perhitungan");
        detailHitung.setActionCommand("Detail Perhitungan");
        detailHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(27, 27, 27))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merkHp, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(memoriHp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12))
                                    .addComponent(hargaHp, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(kameraHp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ramHp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(detailHitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diagram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(diagram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rule)
                .addGap(13, 13, 13)
                .addComponent(detailHitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(102, 102, 102))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(merkHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(memoriHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kameraHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ramHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(36, 36, 36)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasil Kalkulasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 2, 18))); // NOI18N

        kesesuaianLbl.setText(".");

        kesesuaianLbl2.setText(".");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kesesuaianLbl)
                    .addComponent(kesesuaianLbl2))
                .addContainerGap(607, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kesesuaianLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kesesuaianLbl2)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Implementasi Logika Fuzzy untuk ");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pemilihan Smartphone dengan Menggunakan Metode FIS Tsukamoto");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double kesesuaian = new Smartphone(merkHp.getText(),
                Double.valueOf(hargaHp.getText()),
                Double.valueOf(memoriHp.getText()),
                Double.valueOf(kameraHp.getText()),
                Double.valueOf(ramHp.getText())).getPotensi();

        kesesuaian = kesesuaian;
        kesesuaianLbl.setText("Handphone dengan Merk " + merkHp.getText() + " memiliki skor = " + kesesuaian);

        String hasil;
        if (kesesuaian <= 17.5) { //range yang dimasukkan untuk menentukan hasil tinggi rendahnya suatu nilai
            hasil = "NOT RECOMMENDED";
        } else {
            hasil = "RECOMMENDED";
        }
        kesesuaianLbl2.setText("Dinyatakan " + hasil + " untuk Dibeli");
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean isInt(int key) {
        if (key >= 38 && key <= 100) {
            return true;
        } else {
            return false;
        }
    }

    private void hargaHpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaHpKeyReleased
        if (evt.getKeyCode() == 46) {
            try {
                Double.valueOf(hargaHp.getText());
            } catch (Exception e) {
                hargaHp.setText(hargaHp.getText().substring(0, hargaHp.getText().length() - 1));
            }
        } else if (!isInt(evt.getKeyCode())) {
            hargaHp.setText(hargaHp.getText().substring(0, hargaHp.getText().length() - 1));
        }
    }//GEN-LAST:event_hargaHpKeyReleased

    private void memoriHpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memoriHpKeyReleased
        if (evt.getKeyCode() == 46) {
            try {
                Double.valueOf(memoriHp.getText());
            } catch (Exception e) {
                memoriHp.setText(memoriHp.getText().substring(0, memoriHp.getText().length() - 1));
            }
        } else if (!isInt(evt.getKeyCode())) {
            memoriHp.setText(memoriHp.getText().substring(0, memoriHp.getText().length() - 1));
        }
    }//GEN-LAST:event_memoriHpKeyReleased

    private void kameraHpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kameraHpKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 46) {
            try {
                Double.valueOf(kameraHp.getText());
            } catch (Exception e) {
                kameraHp.setText(kameraHp.getText().substring(0, kameraHp.getText().length() - 1));
            }
        } else if (!isInt(evt.getKeyCode())) {
            kameraHp.setText(kameraHp.getText().substring(0, kameraHp.getText().length() - 1));
        }
    }//GEN-LAST:event_kameraHpKeyReleased

    private void ramHpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ramHpKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 46) {
            try {
                Double.valueOf(ramHp.getText());
            } catch (Exception e) {
                ramHp.setText(ramHp.getText().substring(0, ramHp.getText().length() - 1));
            }
        } else if (!isInt(evt.getKeyCode())) {
            ramHp.setText(ramHp.getText().substring(0, ramHp.getText().length() - 1));
        }
    }//GEN-LAST:event_ramHpKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        merkHp.setText("");
        hargaHp.setText("");
        memoriHp.setText("");
        kameraHp.setText("");
        ramHp.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void detailHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailHitungActionPerformed
        JFrame frame2 = new JFrame("Detail Perhitungan");
        frame2.setVisible(true);
        frame2.setSize(770, 360);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        Container konten = getContentPane();

        String field[] = {"Rule", "µ Harga", "µ MemoriInternal", "µ Kamera", "µ RAM", "Potensi Handphone", "Nilai α", "Nilai Z tiap Rule", "α * Z"}; //Membuat Nama Field

        String record[][] = { //rule yang akan menentukan apakah nilai yang dimasukkan termasuk tinggi atau rendah
            {"1", String.valueOf(Rm1[0]), String.valueOf(Rm2[0]), String.valueOf(Rm3[0]), String.valueOf(Rm4[0]), "Recommended", String.valueOf(AlfaTemp[0]), String.valueOf(Zn[0]), String.valueOf(AlfaTemp[0] * Zn[0])},
            {"2", String.valueOf(Rm1[1]), String.valueOf(Rm2[1]), String.valueOf(Rm3[1]), String.valueOf(Rm4[1]), "Recommended", String.valueOf(AlfaTemp[1]), String.valueOf(Zn[1]), String.valueOf(AlfaTemp[1] * Zn[1])},
            {"3", String.valueOf(Rm1[2]), String.valueOf(Rm2[2]), String.valueOf(Rm3[2]), String.valueOf(Rm4[2]), "Recommended", String.valueOf(AlfaTemp[2]), String.valueOf(Zn[2]), String.valueOf(AlfaTemp[2] * Zn[2])},
            {"4", String.valueOf(Rm1[3]), String.valueOf(Rm2[3]), String.valueOf(Rm3[3]), String.valueOf(Rm4[3]), "Not Recommended", String.valueOf(AlfaTemp[3]), String.valueOf(Zn[3]), String.valueOf(AlfaTemp[3] * Zn[3])},
            {"5", String.valueOf(Rm1[4]), String.valueOf(Rm2[4]), String.valueOf(Rm3[4]), String.valueOf(Rm4[4]), "Recommended", String.valueOf(AlfaTemp[4]), String.valueOf(Zn[4]), String.valueOf(AlfaTemp[4] * Zn[4])},
            {"6", String.valueOf(Rm1[5]), String.valueOf(Rm2[5]), String.valueOf(Rm3[5]), String.valueOf(Rm4[5]), "Not Recommended", String.valueOf(AlfaTemp[5]), String.valueOf(Zn[5]), String.valueOf(AlfaTemp[5] * Zn[5])},
            {"7", String.valueOf(Rm1[6]), String.valueOf(Rm2[6]), String.valueOf(Rm3[6]), String.valueOf(Rm4[6]), "Not Recommended", String.valueOf(AlfaTemp[6]), String.valueOf(Zn[6]), String.valueOf(AlfaTemp[6] * Zn[6])},
            {"8", String.valueOf(Rm1[7]), String.valueOf(Rm2[7]), String.valueOf(Rm3[7]), String.valueOf(Rm4[7]), "Not Recommended", String.valueOf(AlfaTemp[7]), String.valueOf(Zn[7]), String.valueOf(AlfaTemp[7] * Zn[7])},
            {"9", String.valueOf(Rm1[8]), String.valueOf(Rm2[8]), String.valueOf(Rm3[8]), String.valueOf(Rm4[8]), "Recommended", String.valueOf(AlfaTemp[8]), String.valueOf(Zn[8]), String.valueOf(AlfaTemp[8] * Zn[8])},
            {"10", String.valueOf(Rm1[9]), String.valueOf(Rm2[9]), String.valueOf(Rm3[9]), String.valueOf(Rm4[9]), "Recommended", String.valueOf(AlfaTemp[9]), String.valueOf(Zn[9]), String.valueOf(AlfaTemp[9] * Zn[9])},
            {"11", String.valueOf(Rm1[10]), String.valueOf(Rm2[10]), String.valueOf(Rm3[10]), String.valueOf(Rm4[10]), "Not Recommended", String.valueOf(AlfaTemp[10]), String.valueOf(Zn[10]), String.valueOf(AlfaTemp[10] * Zn[10])},
            {"12", String.valueOf(Rm1[11]), String.valueOf(Rm2[11]), String.valueOf(Rm3[11]), String.valueOf(Rm4[11]), "Not Recommended", String.valueOf(AlfaTemp[11]), String.valueOf(Zn[11]), String.valueOf(AlfaTemp[11] * Zn[11])},
            {"13", String.valueOf(Rm1[12]), String.valueOf(Rm2[12]), String.valueOf(Rm3[12]), String.valueOf(Rm4[12]), "Not Recommended", String.valueOf(AlfaTemp[12]), String.valueOf(Zn[12]), String.valueOf(AlfaTemp[12] * Zn[12])},
            {"14", String.valueOf(Rm1[13]), String.valueOf(Rm2[13]), String.valueOf(Rm3[13]), String.valueOf(Rm4[13]), "Not Recommended", String.valueOf(AlfaTemp[13]), String.valueOf(Zn[13]), String.valueOf(AlfaTemp[13] * Zn[13])},
            {"15", String.valueOf(Rm1[14]), String.valueOf(Rm2[14]), String.valueOf(Rm3[14]), String.valueOf(Rm4[14]), "Not Recommended", String.valueOf(AlfaTemp[14]), String.valueOf(Zn[14]), String.valueOf(AlfaTemp[14] * Zn[14])},
            {"16", String.valueOf(Rm1[15]), String.valueOf(Rm2[15]), String.valueOf(Rm3[15]), String.valueOf(Rm4[15]), "Not Recommended", String.valueOf(AlfaTemp[15]), String.valueOf(Zn[15]), String.valueOf(AlfaTemp[15] * Zn[15])},
            {"", "", "", "", "", "", "", "TOTAL Z : ", String.valueOf(zA)}
        };

        konten.setLayout(null);
        model = new DefaultTableModel(record, field); // set Model Tabel
        tabel = new JTable(model);

        tabel.setGridColor(Color.BLUE); //Memberi warna garis tabel

        lblApl.setForeground(Color.WHITE);
        lblApl.setBounds(200, 10, 200, 25);
        frame2.add(lblApl);
        scrollPane = new JScrollPane(tabel);
        scrollPane.setBounds(20, 50, 550, 200);
        frame2.add(scrollPane);

        // TODO add your handling code here:
    }//GEN-LAST:event_detailHitungActionPerformed

    private void diagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagramActionPerformed
        // TODO add your handling code here:
        diagram Diagram = new diagram();
        Diagram.setVisible(true);
    }//GEN-LAST:event_diagramActionPerformed

    private void ruleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruleActionPerformed
        JFrame frame2 = new JFrame("Rule");
        frame2.setVisible(true);
        frame2.setSize(670, 360);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        Container konten = getContentPane();

        String field[] = {"Rule", "Harga", "Memori Internal", "Kamera", "RAM", "Potensi Handphone"}; //Membuat Nama Field

        String record[][] = { //rule yang akan menentukan apakah nilai yang dimasukkan termasuk tinggi atau rendah
            {"1", "Tinggi", "Tinggi", "Tinggi", "Tinggi", "Not Recommended"},
            {"2", "Tinggi", "Tinggi", "Tinggi", "Rendah", "Not Recommended"},
            {"3", "Tinggi", "Tinggi", "Rendah", "Tinggi", "Not Recommended"},
            {"4", "Tinggi", "Tinggi", "Rendah", "Rendah", "Not Recommended"},
            {"5", "Tinggi", "Rendah", "Tinggi", "Tinggi", "Not Recommended"},
            {"6", "Tinggi", "Rendah", "Tinggi", "Rendah", "Not Recommended"},
            {"7", "Tinggi", "Rendah", "Rendah", "Tinggi", "Not Recommended"},
            {"8", "Tinggi", "Rendah", "Rendah", "Rendah", "Not Recommended"},
            {"9", "Rendah", "Tinggi", "Tinggi", "Tinggi", "Recommended"},
            {"10", "Rendah", "Tinggi", "Tinggi", "Rendah", "Recommended"},
            {"11", "Rendah", "Tinggi", "Rendah", "Tinggi", "Recommended"},
            {"12", "Rendah", "Tinggi", "Rendah", "Rendah", "Not Recommended"},
            {"13", "Rendah", "Rendah", "Tinggi", "Tinggi", "Recommended"},
            {"14", "Rendah", "Rendah", "Tinggi", "Rendah", "Recommended"},
            {"15", "Rendah", "Rendah", "Rendah", "Tinggi", "Recommended"},
            {"16", "Rendah", "Rendah", "Rendah", "Rendah", "Not Recommended"}
        };

        konten.setLayout(null);
        model = new DefaultTableModel(record, field); // set Model Tabel
        tabel = new JTable(model);

        tabel.setGridColor(Color.black); //Memberi warna garis tabel

        lblApl.setForeground(Color.WHITE);
        lblApl.setBounds(200, 10, 200, 25);
        frame2.add(lblApl);
        scrollPane = new JScrollPane(tabel);
        scrollPane.setBounds(20, 50, 550, 200);
        frame2.add(scrollPane);

        // TODO add your handling code here:
    }//GEN-LAST:event_ruleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogFuz().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailHitung;
    private javax.swing.JButton diagram;
    private javax.swing.JTextField hargaHp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField kameraHp;
    private javax.swing.JLabel kesesuaianLbl;
    private javax.swing.JLabel kesesuaianLbl2;
    private javax.swing.JTextField memoriHp;
    private javax.swing.JTextField merkHp;
    private javax.swing.JTextField ramHp;
    private javax.swing.JButton rule;
    // End of variables declaration//GEN-END:variables

}
